unpackaged/objects/Scanned_Business_Cards__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Used for populating the Name of the Account as indicated on the business card.</description>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated based on matching logic</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scanned Business Cards</relationshipLabel>
        <relationshipName>Scanned_Business_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>Logical one line output of Address fields (Street1, Street2, City, County, Country, Post Code)</description>
        <formula>if(LEN( Street1__c ) &gt; 0, Street1__c &amp; &quot;, &quot; , &quot;&quot; ) &amp;
if(LEN( Street2__c )&gt; 0, Street2__c &amp; &quot;, &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN( City__c )&gt; 0, City__c &amp; &quot;, &quot; , &quot;, &quot; ) &amp; BR() &amp;
if(LEN( Country__c ) &gt; 0, Country__c&amp; &quot;, &quot; , &quot;, &quot; ) &amp; BR() &amp;
If(LEN( Postcode__c ) &gt; 0, Postcode__c, &quot;&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated based on matching logic</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Scanned Business Cards</relationshipLabel>
        <relationshipName>Scanned_Business_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Id__c</fullName>
        <description>Stores the external id of the user who created the record.</description>
        <externalId>true</externalId>
        <label>Created By Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Used for populating the Email of individual as indicated on the business card</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <description>Used for populating the Fax of individual as indicated on the business card</description>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for populating the First Name of individual as indicated on the business card</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>if(LEN( First_Name__c ) &gt; 0, &apos;Salutation &apos; + First_Name__c &amp; &quot;, &quot; , &quot;&quot; ) &amp;
if(LEN( Last_Name__c )&gt; 0, Last_Name__c  &amp; &quot;, &quot; , &quot;&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for populating the Last Name of individual as indicated on the business card</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Used for populating the Mobile of individual as indicated on the business card.</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Used for tracking notes associated to this business card</description>
        <label>Notes</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Used for populating the Phone of individual as indicated on the business card.</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <description>Used for populating the salutation of individual as indicated on the business card</description>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Country__c</fullName>
        <label>State / Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores the status of the business card. Incomplete indicates card has been scanned but not mapped to contact &amp; account, while complete indicates card is scanned and mapped to contact / account</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Used for populating the Title of individual as indicated on the business card</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Scanned Business Card</label>
    <nameField>
        <displayFormat>Card-{00000000}</displayFormat>
        <label>Card Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scanned Business Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ScannedBusinessCardRESTService.cls
global class ScannedBusinessCardRESTService {

	public static void doGet() {

		RestContext.response.addHeader(Constants.HEADER_CONTENT_TYPE, Constants.CONTENT_TYPE_APPLICATION_JSON);

		String userId = RestContext.request.params.get('creatorId');
		String status = RestContext.request.params.get('status');
		String cardId = RestContext.request.params.get('id');

		if (cardId != null && GeneralService.isValid(cardId, Scanned_Business_Cards__c.sObjectType) == false)
		{

			Response.getInstance().setBody(Blob.valueOf(JSON.serialize(new DTOScannedBusinessCard.StatusMessage(
							'Your request is invalid. ' +
							'Make sure that you specified the correct card Id', Constants.HTTP_STATUS_NOT_FOUND))));

			return;
		}

		if (status != null &&
				!GeneralService.listContains(GeneralService.getValuesOfPicklist_ScannedBusinessCard(), status)) {

			Response.getInstance().setBody(Blob.valueOf(JSON.serialize(new DTOScannedBusinessCard.StatusMessage(
							'Your request is invalid. Please check the status. ' +
							'Maybe you entered the status which does not exist. After that again.',
					Constants.HTTP_STATUS_NOT_FOUND))));

			return;
		}

		if (userId != null && status != null && cardId == null) {

			if (!ScannedBusinessCardDAO.getBusinessCardByCreatedByIdAndStatus(userId, status).isEmpty()) {

				Response.getInstance().setBody(Blob.valueOf(JSON.serialize(
								new DTOScannedBusinessCard.CardsList(
										ScannedBusinessCardDAO.getBusinessCardByCreatedByIdAndStatus(userId, status)))));
			} else {

				Response.getInstance().setBody(Blob.valueOf(JSON.serialize(
								new DTOScannedBusinessCard.StatusMessage(
										'By Id of the User, which you specified, were not found any business cards or this User does not exist.'))));
			}
		}

		else if (userId != null && status == null && cardId == null) {

			status = Constants.STATUS_INCOMPLETE;

			if (!ScannedBusinessCardDAO.getBusinessCardByCreatedByIdAndStatus(userId, status).isEmpty()) {
				Response.getInstance().setBody(Blob.valueOf(JSON.serialize(
								new DTOScannedBusinessCard.CardsList(
										ScannedBusinessCardDAO.getBusinessCardByCreatedByIdAndStatus(userId, status)))));
			} else {
				Response.getInstance().setBody(Blob.valueOf(JSON.serialize(
								new DTOScannedBusinessCard.StatusMessage(
										'By Id of the User, which you specified, were not found any business cards or this User does not exist.'))));
			}
		}

		else if (cardId == null) {
			Response.getInstance().setBody(Blob.valueOf(JSON.serialize(new DTOScannedBusinessCard.StatusMessage(
					'Your request is invalid. Please check the URL and method. And train again.',
					Constants.HTTP_STATUS_NOT_FOUND))));
		}

		if (userId == null && status == null && cardId != null) {

			if (!ScannedBusinessCardDAO.getCardByCardId(cardId).isEmpty()) {
				Response.getInstance().setBody(Blob.valueOf(JSON.serialize(
								new DTOScannedBusinessCard.CardItemListFull(
										ScannedBusinessCardDAO.getCardByCardId(cardId)))));
			} else {
				Response.getInstance().setBody(Blob.valueOf(JSON.serialize(
								new DTOScannedBusinessCard.StatusMessage(
										'By Id of the Card, which you specified, were not found any business card.'))));
			}
		}

		else if (userId == null && status == null) {
			Response.getInstance().setBody(Blob.valueOf(JSON.serialize(new DTOScannedBusinessCard.StatusMessage(
							'Your request is invalid. Please check the URL and method. Also make sure that you entered required parameters.' +
							'After that train again.', Constants.HTTP_STATUS_NOT_FOUND))));
		}

	}

	public static void doPost() {

		Scanned_Business_Cards__c result = new Scanned_Business_Cards__c();

		RestRequest req = RestContext.request;

		ScannedBusinessCardDTO data = (ScannedBusinessCardDTO) Request.getInstance().getBodyAsClass(ScannedBusinessCardDTO.class );

		if (data.cardId != null && !GeneralService.isValid(data.cardId, Scanned_Business_Cards__c.sObjectType)) {
			Response.getInstance().setBody(Blob.valueOf(JSON.serialize(new DTOScannedBusinessCard.StatusMessage(
					'Your request is invalid. Make sure that you specified the correct card Id. After that try again.'))));
			return;
		}

		if (data.cardId != null) {
			result = [SELECT Salutation__c,
					First_Name__c, Last_Name__c,
					Full_Name__c, Account_Name__c,
					Title__c, Phone__c,
					Mobile__c, Fax__c,
					Email__c, Website__c,
					Street1__c, Street2__c,
					City__c, State_Country__c,
					Country__c, Postcode__c, Address__c,
					Created_By_Id__c
					FROM Scanned_Business_Cards__c WHERE Id = :data.cardId];

			if (data.salutation != null) {
				result.Salutation__c = data.salutation;
			}
			if (data.firstName != null) {
				result.First_Name__c = data.firstName;
			}
			if (data.lastName != null) {
				result.Last_Name__c = data.lastName;
			}
			if (data.accountName != null) {
				result.Account_Name__c = data.accountName;
			}
			if (data.title != null) {
				result.Title__c = data.title;
			}
			if (data.phone != null) {
				result.Phone__c = data.phone;
			}
			if (data.mobile != null) {
				result.Mobile__c = data.mobile;
			}
			if (data.fax != null) {
				result.Fax__c = data.fax;
			}
			if (data.email != null) {
				result.Email__c = data.email;
			}
			if (data.website != null) {
				result.Website__c = data.website;
			}
			if (data.street1 != null) {
				result.Street1__c = data.street1;
			}
			if (data.street2 != null) {
				result.Street2__c = data.street2;
			}
			if (data.city != null) {
				result.City__c = data.city;
			}
			if (data.stateCountry != null) {
				result.State_Country__c = data.stateCountry;
			}
			if (data.country != null) {
				result.Country__c = data.country;
			}
			if (data.postcode != null) {
				result.Postcode__c = data.postcode;
			}
			if (data.notes != null) {
				result.Notes__c = data.notes;
			}
			if (data.createdById != null) {
				result.Created_By_Id__c = data.createdById;
			}
			if (data.status != null) {
				result.Status__c = data.status;
			}
			if (data.accountId != null) {
				result.Account__c = data.accountId;
			}
			if (data.contactId != null) {
				result.Contact__c = data.contactId;
			}

		} else {
			result.Salutation__c = data.salutation;
			result.First_Name__c = data.firstName;
			result.Last_Name__c = data.lastName;
			result.Account_Name__c = data.accountName;
			result.Title__c = data.title;
			result.Phone__c = data.phone;
			result.Mobile__c = data.mobile;
			result.Fax__c = data.fax;
			result.Email__c = data.email;
			result.Website__c = data.website;
			result.Street1__c = data.street1;
			result.Street2__c = data.street2;
			result.City__c = data.city;
			result.State_Country__c = data.stateCountry;
			result.Country__c = data.country;
			result.Postcode__c = data.postcode;
			result.Notes__c = data.notes;
			result.Created_By_Id__c = data.createdById;
			result.Status__c = data.status;
			result.Account__c = data.accountId;
			result.Contact__c = data.contactId;
		}

		upsert result;

		Response.getInstance().setBody(Blob.valueOf(JSON.serialize(
						new DTOScannedBusinessCard.CardItemListFull(
								ScannedBusinessCardDAO.getCardByCardId(result.Id)
						))));
	}

}